name: Gatilho Base BTG

on:
  workflow_dispatch:
  schedule:
    - cron: '55 17 * * *'  # 14:55 BRT

jobs:
  disparar_base_btg:
    runs-on: ubuntu-latest
    steps:
      - name: Disparando Base BTG
        run: |
          echo "Solicitando Base de Clientes..."
          curl -X GET "https://weebhook-btg.onrender.com/trigger/basebtg?token=583cc82acd14cc115a2f6b2e1cda1ee3"